---
output:
  pdf_document: default
  html_document: default
---
```{r, include=F}
# Placeholder for clinical evaluation
# = history and physical
# Nutritional evaluation
```
# CMC Inpatient

Colorectal Surgery (Davis/Kasten) and GI Surgical Oncology (Hill/Salo/Squires) will cover Pineville and CMC. For efficiency, the services at each hospital will merge for patient care. Each patient will continue to have an attending surgeon, but rounding and inpatient care will be provided by the service.

In general Dr Kasten will round on his own patients at CMC.  Dr Davis will round on his own patients if he is at CMC.

## Admissions

Admitting Provider: “CMC GI SURGICAL ONCOLOGY”

List Attending Surgeon in addition

Patient List is CMC GI Surgical Oncology

## Rounds

Attending rounds for both services (CR and SurgOnc) start at 6am in STICU or 11T.  Dr Salo rounds M-Tu and Drs Squires and Hill round  W/Th/F alternate weeks

## Resident Halo teams:

CMC AH Colorectal Surgery 1st Call
CMC LCI GI Surgical Oncology 1st Call
Residents will be assigned to Halo teams by schedule. It is critical that you notify service attendings before the start of the month to adjust the resident Halo schedule. Each “shift” is 5:50am to 6pm. At 6pm the resident Halo Teams will be forwarded to the night team.

Please append a text block to the bottom of each progress note specifying the Halo Team for that patient to facilitate communication from nursing.

## Attending Halo teams:

CMC AH Colorectal Surgery Attending
CMC LCI GI Surgical Oncology Attending
Monday through Thursday (24hr), please contact the attending surgeon for each patient. For Surgical Oncology, please use Halo. For Colorectal, please use phone.

Friday and Weekend: Halo “CMC GI MIS Blue Surgery Attending Colorectal Onc” for new admissions. Please keep Surgical Oncology attending informed of inpatient issues.

## Consults

Established patients and directed should be discussed with the attending surgeon.

Unassigned Colorectal: “CMC AH Colorectal Surgery Attending”

Unassigned Surgical Oncology: “CMC LCI GI Surgical Oncology Attending”

In general, benign colorectal consults are staffed by Dr Davis. Colorectal malignancies ares.
 staffed as below. Esophageal and GE junction staffed by Dr Salo. Adenocarcinoma of distal stomach: Drs Salo/Squires. Gastric GIST: Drs Hill/Salo/Squires. Squires/Hill alternate week
|  | Mon | Tues | Weds | Thu | Fri |
|---|---|---|---|---|---|
| CR Malig | JSH | MHS | MHS<br>JSH | JCS | MHS<br>JSH |
| GI Surg Onc | JSH | MHS | MHS<br>JSH | JCS | MHS<br>JSH |

## Postop Clinic Appts

Postoperative patients are generally seen for a Transition of Care visit within the first week

Discharge appointments are made by sending a message in Canopy the evening prior (preferred) OR the morning of discharge before 8am to:

**January 2022** Due to transitions in Dr Hill's clinic staffing, please send messages for discharges directly to him, and he will forward.

- LCI CMC GI, Clerical
- Marsha Sukhdeo (Salo and Squires)
- Amanda Asmar (Salo and Squires) - Until April 2022
- Sara Gaddy (Salo and Squires) - Starting April 2022
- Rebecca Wicks (Hill) - Starting April 2022
- Brenda Prieto
- Brandon Galloway

Please include the following information in the Canopy Message:

- Name of attending
- Ward from which the patient is being discharged
- Desired date for appointment
- Need for Wound Ostomy RN appointment at same time (essential for new stomas)
- Need for bloodwork at first
- Other studies to be done after discharge
  - Upper GI
  - Chest X-ray
  - Modified Barium Swallow

If messages cannot be sent in time, clinic schedulers can be reached at: Marsha Sukhdeo (Salo and Squires): 980-442-6110 or  (Hill): 980-442-6183.

If schedulers are not available, clinic RNs can be reached at:   (Hill) 980-442-6146 or (Sa visitlo and Squires) 980-442-6143.

For patients likely to go home over the weekend or holidays, please plan to send a canopy message before 3pm on Friday or the day prior.

The scheduler will respond with a message to the discharging resident AND to the ward CNL with the appointment time, which can be included within the discharge summary. Copies of the message will also be sent to clinical nurse leaders:

- 11Tower: Sharon Hood
- 6Tower: Amy Peterson



## Conferences

- GI Tumor Planning Conference Monday 7-8am
- Resident Teaching Conference Tuesday 7-8am 5th floor LCI II. Please review the upcoming clinic schedule and choose a case to present.
- Bone and Soft Tissue Conference Friday 7-8am
