---
output:
  html_document: default
  pdf_document: default
---
```{r, include=F}
# Placeholder for clinical evaluation
# = history and physical
# Nutritional evaluation
```
# Discharges

**Discharge Prescriptions**

Prescriptions should be ideally be prepared the day prior to anticipated discharge and left in the patient’s ‘soft chart.’ According to North Carolina STOP guidelines, opioid prescriptions for postoperative patients should be for no more than a 7 day supply.


**Additional Appointments**

If followup appointments in additional to surgical followup are needed, these should be designated on the discharge orders. Particularly:

- Primary Care Physician
- Cardiologist (if new cardiac medicines)
- Co-surgeons (Urology, Thoracic Surgery, GYN)

**Discharge Summary**

The discharge summary documents important events and complications in the postoperative course and serves to inform the referring physician and primary physician about these events, but also serves as a blueprint for post-discharge treatment planning. Please recognize that the first post-operative visit may be with a resident who may be meeting the patient for the first time. Key items to include:

|||
|----|-----------------------------------------------------------------|
| N  | Followup plan for chronic pain management                  |
|    | Stroke                                                         |
| CV | Postop Arrhythmia? \| MI? \| CHF?                                          |
|    | If new cardiac meds: Who is managing medications               |
|    | If afib: CHADS score and anticoagulation plan              |
| R  | Pneumonia? \| ARDS? \|  TRACH? |
|    | Need for home oxygen?                                          |
|    | CXR needed at first postop visit?                                                  |
|GI	|Delayed gastric emptying? \| leak? \| ileus?|
|    |Tube feed regimen|
|     |Diet at discharge (Low residue \| Full liquds \| Meds with thickened water \|NPO)|
|   |New stoma (ileostomy \| colostomy)|
|     |Wound care needs (VAc \| Prevena)
|GU	|Urinary Retention|
|  |Discharge with foley catheter|
|H	|Complications: DVT \| PE|
|   |Anticoagulation Plan|
|Endo|Insulin regimen at DC (dose will be in med rec)|
|ID|Antibiotics at DC|
||Return to ICU|


**Communication**

It is essential that discharge summaries be sent to the patient’s primary MD and referring physician. Please review the initial consultation note for the names of providers involved in a patient’s care.

In order to easily access the patient’s providers, please prepare a “]Providers” autotext:

Click the AutoText icon on a document
Add new AutoText by clicking the blue + sign
Create a name for the new AutoText (such as “]Providers”)
Select a smart template by clicking the second icon from the right of the buttons
Search for “Transition” and select “Transition Clinic Header”
Save the AutoText
Please paste the ]Providers AutoText in the body of the discharge summary to easily access who should receive copies of the discharge summary
