# (PART\*) Gastric Cancer {-}

# Gastric Ca SCORE

[Gastric Cancer SCORE](http://portal.surgicalcore.org/modulecontent.aspx?id=128003)

**Anatomy**

- Lymph node stations
- D1 vs D2 vs D3 nodal basins

**Epidemiology**

- Worldwide distribution
- Risk factors

**Diagnosis and Staging**

- Nodal staging number vs location
- Role of PET scan
- Role of laparoscopy

**Operative Treatment**

- Reconstruction options

**Non-operative Treatments**

- Palliative chemotherapy
- Stents

[Gastrectomy SCORE](http://portal.surgicalcore.org/modulecontent.aspx?id=146287)

**Operative Anatomy**

**Preoperative Preparation**

**Operative Details**

**Complications**

- Anastomotic leak
- Bleeding
- Obstruction
- Afferent Loop Syndrome
- Dumping
- Alkaline reflux gastritis

[GIST SCORE](http://portal.surgicalcore.org/modulecontent.aspx?id=136240)

**GI stromal tumors**

- Pathology: Cell of origin/IHC
- Operative treatment

**Gastric carciniods**

- Pathology - Cell of origin
- Type I
- Type II
- Type III
- Role for endoscopic therapy
- Surgery
  - Tumor resection
  - Antrectomy

**Gastric lymphoma**

- Low-grade vs high-grade MALT vs non-MALT
- Treatment: operative/non-op
- Indications for surgery

**Gastric Polyps**

- Indications for resection
- Non-operative treatment of hyperplastic polyps
- SMAD4 mutations
