# Hereditary Diffuse Gastric Cancer

HDGC is a syndrome characterized by early-onset diffuse gastric cancer and increased risk of lobular breast cancer.

Hereditary diffuse gastric cancer was first reported in a New Zealand Maori cohort.  The genetic cause was subsequently found to the a deletion in the CDH1 gene.

### Penetrance estimates for lifetime risk of DGC

The original estimates of lifetime risk of gastric cancer in those with pathogenic CDH1 mutations were made from a population of patients with strong familiy histories of DGC[@hansford23], in this group, 
the cumulative risk of gastric cancer by 80 years of age was estimated to be to be 70% in men and 56% in women.

The lifetime risk of gastric cancer in more modern cohorts[@roberts1325] [@xicola838], in whom a minority of patients have a family history of gastric cancer, are much lower: 42% in men and 33% in women


## Surveillance for CDH1 carriers

Cancer surveillance as an alternative to prophylactic total  gastrectomy in hereditary diffuse gastric cancer:  a prospective cohort study  Bilal Asif*, Amber Leila Sarvestani*, Lauren A Gamble, Sarah G Samaranayake, Amber L Famiglietti, Grace-Ann Fasaye, Martha Quezado, Markku Miettinen, Louis Korman, Christopher Koh, Theo Heller, Jeremy L Davis  Summary  Background Loss of function variants in CDH1 are the most frequent cause of hereditary diffuse gastric cancer. Endoscopy is regarded as insufficient for early detection due to the infiltrative phenotype of diffuse-type cancers. Microscopic foci of invasive signet ring cells are pathognomonic of CDH1 and precede development of diffuse gastric cancer. We aimed to assess the safety and effectiveness of endoscopy for cancer interception in individuals with germline CDH1 variants, particularly in those who declined prophylactic total gastrectomy.  Methods In this prospective cohort study, we included asymptomatic patients aged 2 years or older with pathogenic or likely pathogenic germline CDH1 variants who underwent endoscopic screening and surveillance at the National Institutes of Health (Bethesda, MD, USA) as part of a natural history study of hereditary gastric cancers (NCT03030404). Endoscopy was done with non-targeted biopsies and one or more targeted biopsy and assessment of focal lesions. Endoscopy findings, pathological data, personal and family cancer history, and demographics were recorded. Procedural morbidity, gastric cancer detection by endoscopy and gastrectomy, and cancer-specific events were assessed. Screening was defined as the initial endoscopy and all subsequent endoscopies were considered surveillance; follow-up endoscopy was at 6 to 12 months. The primary aim was to determine effectiveness of endoscopic surveillance for detection of gastric signet ring cell carcinoma.  Findings Between Jan 25, 2017, and Dec 12, 2021, 270 patients (median age 46·6 years [IQR 36·5–59·8], 173 [64%] female participants, 97 [36%] male participants; 250 [93%] were non-Hispanic White, eight [3%] were multiracial, four [2%] were non-Hispanic Black, three [1%] were Hispanic, two [1%] were Asian, and one [<1%] was American Indian or Alaskan Native) with germline CDH1 variants were screened, in whom 467 endoscopies were done as of data cutoff (April 30, 2022). 213 (79%) of 270 patients had a family history of gastric cancer, and 176 (65%) reported a family history of breast cancer. Median follow-up was 31·1 months (IQR 17·1–42·1). 38 803 total gastric biopsy samples were obtained, of which 1163 (3%) were positive for invasive signet ring cell carcinoma. Signet ring cell carcinoma was detected in 76 (63%) of 120 patients who had two or more surveillance endoscopies, of whom 74 had occult cancer detected; the remaining two individuals developed focal ulcerations each corresponding to pT3N0 stage carcinoma. 98 (36%) of 270 patients proceeded to prophylactic total gastrectomy. Among patients who had a prophylactic total gastrectomy after an endoscopy with biopsy samples negative for cancer (42 [43%] of 98), multifocal stage IA gastric carcinoma was detected in 39 (93%). Two (1%) participants died during follow-up, one due to metastatic lobular breast cancer and the other due to underlying cerebrovascular disease, and no participants were diagnosed with advanced stage (III or IV) cancer during follow-up.  Interpretation In our cohort, endoscopic cancer surveillance was an acceptable alternative to surgery in individuals with CDH1 variants who declined total gastrectomy. The low rate of incident tumours (>T1a) suggests that...
