# Stage IV Colon Cancer

## Carcinomatosis

## Colon resection in stage IV colon cancer

MSKCC: Colon surgery patients with bilobar liver metastasis treated with chemotherapy with primary tumor in place. Surgical intervention needed in 7% of cases [@poultsides35]

## Immunotherapy for dMMR (MSI high)

Colorectal cancers deficient in mismatch-repair proteins (dMMR) respond poorly to 5FU-based chemotherapy but do respond to immune-checkpoint inhibitors ($\alpha$-PD-1, ($\alpha$PD-L1, ($\alpha$-CTLA-4).

[Review](https://www.frontiersin.org/articles/10.3389/fimmu.2022.795972/full) of immune checkpoint inhibitors in colorectal cancer

Blockade of the PD-1 (Programmed Death-1) ligand with monoclonal antibody as shows efficacy in colorectal cancer, especially those deficient in mismatch repair protein expression, as manifested by microsatellite instability (MSI-High) on pathologic exam.

Keynote-177 trial [@andre2207] randomized 307 patients with MSI-High dMMR colorectal cancer patients to receive either pembrolizumab or 5-FU based chemeotherapy and found superior survival with pembro.


