
# Rectal Cancer Staging

## MRI staging

Rectal cancer is preferentially evaluated with MRI. At Atrium, this is ordered as "MRI Pelvis without Contrast Rectal Protocol"

Key findings

- Circumferential resection margin
- Extra mesorectal vascular invasion
- Mesorectal lymph nodes
- Extra-mesorectal lymph nodes

MRI has supplanted endoscopic ultrasound (EUS) as the study of choice for staging rectal cancer.

MERCURY group trial demonstrated the predictive value of MRI for rectal cancer[@taylor34] [@mercurystudygroup779]

## EUS

Endoscopic ultrasound has now been replaced by MRI for initial staging, in part due to intraoperater variability

# Rectal Cancer Surgery

Importance of total mesorectal excision was championed by Bill Heald [@heald1479] who emphasized sharp dissection of the mesorecum outside of the visceral fasial envelope.  In addition he advocated dissection of the totality of the mesorectum distal to the tumor to avoid leaving behind nodes within the mesorectum distal to the tumor[@quirke996] [@nagtegaal303] [@paty365].


