---
output:
  pdf_document: default
  html_document: default
---
# Non-operative management of Rectal Cancer

MSKCC published an experience of 113 patients with cCR after chemoradiation for rectal cancer who elected non-operative management [@smithe185896]. Among this group, 22 developed a local recurrence, and 8% developed metastatic disease.[@smith657]

A new paradigm for rectal cancer: Organ preservation
Introducing the International Watch & Wait Database (IWWD) [@beets1562]



    Habr-Gama A.
    Gama-Rodrigues J.
    Sao Juliao G.P.
    et al.

Local recurrence after complete clinical response and watch and wait in rectal cancer after neoadjuvant chemoradiation: impact of salvage therapy on local disease control.
Int J Radiat Oncol Biol Phys. Mar 15 2014; 88: 822-828
View in Article

  

    Maas M.
    Beets-Tan R.G.
    Lambregts D.M.
    et al.

Wait-and-see policy for clinical complete responders after chemoradiation for rectal cancer.
J Clin Oncol. Dec 10 2011; 29: 4633-4640
View in Article

    Scopus (791)
    PubMed
    Crossref
    Google Scholar

    Appelt A.L.
    Ploen J.
    Harling H.
    et al.

High-dose chemoradiotherapy and watchful waiting for distal rectal cancer: a prospective observational study.
Lancet Oncol. Aug 2015; 16: 919-927
View in Article

    Scopus (392)
    PubMed
    Abstract
    Full Text
    Full Text PDF
    Google Scholar

    Smith J.D.
    Ruby J.A.
    Goodman K.A.
    et al.



Surveillance after neoadjuvant therapy in advanced rectal cancer with complete clinical response can have comparable outcomes to total mesorectal excision.
Int J Colorectal Dis. Jun 2015; 30: 769-774
